name: d4_path
version: 1.0.0
description: Serialize Canvas path commands to SVG.
repository: https://github.com/luizbarboza/d4_path

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0